version: 2
updates:
  - package-ecosystem: npm
    directory: /src/frontend/collectify-desktop
    schedule:
      interval: weekly
    open-pull-requests-limit: 5

  - package-ecosystem: nuget
    directory: /src/backend/Collectify.Api
    schedule:
      interval: weekly
    open-pull-requests-limit: 5

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
